name: Deploy to IPFS

permissions:
  contents: read
  pull-requests: write
  statuses: write

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to IPFS
        uses: ipfs/ipfs-deploy-action@v1
        id: deploy
        with:
          kubo-api-url: ${{ secrets.KUBO_API_URL }}
          kubo-api-auth: ${{ secrets.KUBO_API_AUTH }}
          github-token: ${{ github.token }}
