on: [push]

jobs:
  ipfs_publisher_job:
    runs-on: ubuntu-latest
    name: A job to publish the static site to IPFS
    steps:
    - id: checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - id: publish
      uses: sha224/ipfs-publisher@v1
      env:
        DEFAULT_BRANCH: master
        kubo-api-url: ${{ secrets.KUBO_API_URL }}
        kubo-api-auth: ${{ secrets.KUBO_API_AUTH }}
